from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from insightengine.db import DEFAULT_DATABASE_URL, connect, redact_url

try:
    from scripts.analyze_messages import read_jsonl
    from scripts.build_message_features import extract_message_features
    from scripts.profile_export import STOPWORDS, tokenize
except ModuleNotFoundError:  # pragma: no cover - supports direct script execution
    from analyze_messages import read_jsonl
    from build_message_features import extract_message_features
    from profile_export import STOPWORDS, tokenize


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_path TEXT NOT NULL UNIQUE,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS conversations (
    conversation_id TEXT PRIMARY KEY,
    import_id BIGINT REFERENCES imports(id) ON DELETE SET NULL,
    title TEXT,
    create_time TIMESTAMPTZ,
    update_time TIMESTAMPTZ,
    source_file TEXT,
    source_index INTEGER,
    message_count INTEGER NOT NULL DEFAULT 0,
    user_message_count INTEGER NOT NULL DEFAULT 0,
    assistant_message_count INTEGER NOT NULL DEFAULT 0,
    total_words INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS messages (
    message_id TEXT NOT NULL,
    conversation_id TEXT NOT NULL REFERENCES conversations(conversation_id)
        ON DELETE CASCADE,
    parent_id TEXT,
    role TEXT,
    create_time TIMESTAMPTZ,
    update_time TIMESTAMPTZ,
    content_type TEXT,
    text TEXT NOT NULL,
    text_sha256 TEXT NOT NULL,
    word_count INTEGER NOT NULL,
    char_count INTEGER NOT NULL,
    PRIMARY KEY (conversation_id, message_id)
);

CREATE TABLE IF NOT EXISTS message_features (
    message_id TEXT NOT NULL,
    conversation_id TEXT NOT NULL REFERENCES conversations(conversation_id)
        ON DELETE CASCADE,
    parent_id TEXT,
    role TEXT,
    create_time TIMESTAMPTZ,
    month TEXT,
    content_type TEXT,
    text_sha256 TEXT,
    word_count INTEGER NOT NULL,
    char_count INTEGER NOT NULL,
    sentence_count INTEGER NOT NULL,
    average_sentence_words DOUBLE PRECISION NOT NULL,
    question_mark_count INTEGER NOT NULL,
    has_question_mark BOOLEAN NOT NULL,
    uncertainty_marker_count INTEGER NOT NULL,
    reasoning_marker_count INTEGER NOT NULL,
    code_block_count INTEGER NOT NULL,
    url_count INTEGER NOT NULL,
    question_type TEXT NOT NULL,
    PRIMARY KEY (conversation_id, message_id),
    FOREIGN KEY (conversation_id, message_id)
        REFERENCES messages(conversation_id, message_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_id
    ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_role_create_time
    ON messages(role, create_time);
CREATE INDEX IF NOT EXISTS idx_message_features_month
    ON message_features(month);
CREATE INDEX IF NOT EXISTS idx_message_features_question_type
    ON message_features(question_type);
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Postgres storage utilities.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Create database tables.")
    add_database_url_arg(init_parser)

    reset_parser = subparsers.add_parser(
        "reset",
        help="Drop and recreate database tables for local development.",
    )
    add_database_url_arg(reset_parser)

    load_parser = subparsers.add_parser(
        "load-jsonl",
        help="Load normalized local JSONL files into Postgres.",
    )
    add_database_url_arg(load_parser)
    load_parser.add_argument(
        "--import-source",
        default="data/processed",
        help="Stable source label for this local import.",
    )
    load_parser.add_argument(
        "--conversations",
        type=Path,
        default=Path("data/processed/conversations.jsonl"),
        help="Path to conversations.jsonl.",
    )
    load_parser.add_argument(
        "--messages",
        type=Path,
        default=Path("data/processed/messages.jsonl"),
        help="Path to messages.jsonl.",
    )

    analyze_parser = subparsers.add_parser(
        "analyze",
        help="Run deterministic aggregate analyses from Postgres.",
    )
    add_database_url_arg(analyze_parser)
    analyze_parser.add_argument("--search", help="Optional user-message keyword search.")
    analyze_parser.add_argument(
        "--top-terms",
        type=int,
        default=25,
        help="Number of top user-message terms to include.",
    )

    args = parser.parse_args()

    if args.command == "init":
        init_db(args.database_url)
        print(json.dumps({"status": "ok", "database_url": redact_url(args.database_url)}))
    elif args.command == "reset":
        reset_db(args.database_url)
        print(json.dumps({"status": "ok", "database_url": redact_url(args.database_url)}))
    elif args.command == "load-jsonl":
        result = load_jsonl(
            args.database_url,
            args.import_source,
            args.conversations,
            args.messages,
        )
        print(json.dumps(result, indent=2, ensure_ascii=False))
    elif args.command == "analyze":
        result = analyze_db(
            args.database_url,
            search=args.search,
            top_terms=args.top_terms,
        )
        print(json.dumps(result, indent=2, ensure_ascii=False))


def add_database_url_arg(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--database-url",
        default=os.environ.get("DATABASE_URL", DEFAULT_DATABASE_URL),
        help="Postgres connection URL. Defaults to local Docker Compose settings.",
    )


def init_db(database_url: str) -> None:
    with connect(database_url) as conn:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)


def reset_db(database_url: str) -> None:
    with connect(database_url) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                DROP TABLE IF EXISTS message_features;
                DROP TABLE IF EXISTS messages;
                DROP TABLE IF EXISTS conversations;
                DROP TABLE IF EXISTS imports;
                """
            )
            cur.execute(SCHEMA_SQL)


def load_jsonl(
    database_url: str,
    import_source: str,
    conversations_path: Path,
    messages_path: Path,
) -> dict[str, Any]:
    init_db(database_url)
    conversations = list(read_jsonl(conversations_path))
    messages = list(read_jsonl(messages_path))

    with connect(database_url) as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO imports (source_path)
                VALUES (%s)
                ON CONFLICT (source_path)
                DO UPDATE SET imported_at = now()
                RETURNING id
                """,
                (import_source,),
            )
            import_id = cur.fetchone()["id"]

            for conversation in conversations:
                cur.execute(
                    """
                    INSERT INTO conversations (
                        conversation_id,
                        import_id,
                        title,
                        create_time,
                        update_time,
                        source_file,
                        source_index,
                        message_count,
                        user_message_count,
                        assistant_message_count,
                        total_words
                    )
                    VALUES (
                        %(conversation_id)s,
                        %(import_id)s,
                        %(title)s,
                        %(create_time)s,
                        %(update_time)s,
                        %(source_file)s,
                        %(source_index)s,
                        %(message_count)s,
                        %(user_message_count)s,
                        %(assistant_message_count)s,
                        %(total_words)s
                    )
                    ON CONFLICT (conversation_id) DO UPDATE SET
                        import_id = EXCLUDED.import_id,
                        title = EXCLUDED.title,
                        create_time = EXCLUDED.create_time,
                        update_time = EXCLUDED.update_time,
                        source_file = EXCLUDED.source_file,
                        source_index = EXCLUDED.source_index,
                        message_count = EXCLUDED.message_count,
                        user_message_count = EXCLUDED.user_message_count,
                        assistant_message_count = EXCLUDED.assistant_message_count,
                        total_words = EXCLUDED.total_words
                    """,
                    {**conversation, "import_id": import_id},
                )

            for message in messages:
                cur.execute(
                    """
                    INSERT INTO messages (
                        message_id,
                        conversation_id,
                        parent_id,
                        role,
                        create_time,
                        update_time,
                        content_type,
                        text,
                        text_sha256,
                        word_count,
                        char_count
                    )
                    VALUES (
                        %(message_id)s,
                        %(conversation_id)s,
                        %(parent_id)s,
                        %(role)s,
                        %(create_time)s,
                        %(update_time)s,
                        %(content_type)s,
                        %(text)s,
                        %(text_sha256)s,
                        %(word_count)s,
                        %(char_count)s
                    )
                    ON CONFLICT (conversation_id, message_id) DO UPDATE SET
                        parent_id = EXCLUDED.parent_id,
                        role = EXCLUDED.role,
                        create_time = EXCLUDED.create_time,
                        update_time = EXCLUDED.update_time,
                        content_type = EXCLUDED.content_type,
                        text = EXCLUDED.text,
                        text_sha256 = EXCLUDED.text_sha256,
                        word_count = EXCLUDED.word_count,
                        char_count = EXCLUDED.char_count
                    """,
                    message,
                )

                feature = extract_message_features(message)
                cur.execute(
                    """
                    INSERT INTO message_features (
                        message_id,
                        conversation_id,
                        parent_id,
                        role,
                        create_time,
                        month,
                        content_type,
                        text_sha256,
                        word_count,
                        char_count,
                        sentence_count,
                        average_sentence_words,
                        question_mark_count,
                        has_question_mark,
                        uncertainty_marker_count,
                        reasoning_marker_count,
                        code_block_count,
                        url_count,
                        question_type
                    )
                    VALUES (
                        %(message_id)s,
                        %(conversation_id)s,
                        %(parent_id)s,
                        %(role)s,
                        %(create_time)s,
                        %(month)s,
                        %(content_type)s,
                        %(text_sha256)s,
                        %(word_count)s,
                        %(char_count)s,
                        %(sentence_count)s,
                        %(average_sentence_words)s,
                        %(question_mark_count)s,
                        %(has_question_mark)s,
                        %(uncertainty_marker_count)s,
                        %(reasoning_marker_count)s,
                        %(code_block_count)s,
                        %(url_count)s,
                        %(question_type)s
                    )
                    ON CONFLICT (conversation_id, message_id) DO UPDATE SET
                        parent_id = EXCLUDED.parent_id,
                        role = EXCLUDED.role,
                        create_time = EXCLUDED.create_time,
                        month = EXCLUDED.month,
                        content_type = EXCLUDED.content_type,
                        text_sha256 = EXCLUDED.text_sha256,
                        word_count = EXCLUDED.word_count,
                        char_count = EXCLUDED.char_count,
                        sentence_count = EXCLUDED.sentence_count,
                        average_sentence_words = EXCLUDED.average_sentence_words,
                        question_mark_count = EXCLUDED.question_mark_count,
                        has_question_mark = EXCLUDED.has_question_mark,
                        uncertainty_marker_count = EXCLUDED.uncertainty_marker_count,
                        reasoning_marker_count = EXCLUDED.reasoning_marker_count,
                        code_block_count = EXCLUDED.code_block_count,
                        url_count = EXCLUDED.url_count,
                        question_type = EXCLUDED.question_type
                    """,
                    feature,
                )

    return {
        "status": "ok",
        "database_url": redact_url(database_url),
        "import_source": import_source,
        "conversation_count": len(conversations),
        "message_count": len(messages),
    }


def analyze_db(
    database_url: str,
    search: str | None = None,
    top_terms: int = 25,
) -> dict[str, Any]:
    with connect(database_url) as conn:
        with conn.cursor() as cur:
            cur.execute("SELECT count(*) AS count FROM conversations")
            conversation_count = cur.fetchone()["count"]
            cur.execute("SELECT count(*) AS count FROM messages")
            message_count = cur.fetchone()["count"]
            cur.execute("SELECT role, count(*) AS count FROM messages GROUP BY role")
            role_counts = {row["role"] or "unknown": row["count"] for row in cur.fetchall()}
            cur.execute(
                """
                SELECT month, count(*) AS count
                FROM message_features
                WHERE month IS NOT NULL
                GROUP BY month
                ORDER BY count DESC, month
                LIMIT 10
                """
            )
            busiest_months = {row["month"]: row["count"] for row in cur.fetchall()}
            cur.execute(
                """
                SELECT
                    month,
                    round(avg(word_count)::numeric, 2) AS average_words,
                    round(
                        (sum(uncertainty_marker_count)::numeric
                        / nullif(sum(word_count), 0)) * 1000,
                        2
                    ) AS uncertainty_markers_per_1000_words
                FROM message_features
                WHERE role = 'user' AND month IS NOT NULL
                GROUP BY month
                ORDER BY month
                """
            )
            trends_by_month = cur.fetchall()
            cur.execute(
                """
                SELECT question_type, count(*) AS count
                FROM message_features
                WHERE role = 'user'
                GROUP BY question_type
                ORDER BY count DESC, question_type
                """
            )
            question_type_counts = {
                row["question_type"]: row["count"] for row in cur.fetchall()
            }
            cur.execute(
                """
                SELECT text
                FROM messages
                WHERE role = 'user' AND text <> ''
                """
            )
            user_terms = Counter()
            for row in cur.fetchall():
                user_terms.update(token for token in tokenize(row["text"]) if token not in STOPWORDS)

            result: dict[str, Any] = {
                "database_url": redact_url(database_url),
                "conversation_count": conversation_count,
                "message_count": message_count,
                "role_counts": role_counts,
                "busiest_months": busiest_months,
                "question_type_counts": question_type_counts,
                "monthly_user_trends": [
                    {
                        "month": row["month"],
                        "average_words": float(row["average_words"]),
                        "uncertainty_markers_per_1000_words": float(
                            row["uncertainty_markers_per_1000_words"] or 0
                        ),
                    }
                    for row in trends_by_month
                ],
                "top_user_terms": user_terms.most_common(top_terms),
            }

            if search:
                cur.execute(
                    """
                    SELECT conversation_id, count(*) AS hit_count
                    FROM messages
                    WHERE role = 'user' AND text ILIKE %s
                    GROUP BY conversation_id
                    ORDER BY hit_count DESC, conversation_id
                    LIMIT 10
                    """,
                    (f"%{search}%",),
                )
                top_matches = cur.fetchall()
                cur.execute(
                    """
                    SELECT count(DISTINCT conversation_id) AS conversations,
                           count(*) AS messages
                    FROM messages
                    WHERE role = 'user' AND text ILIKE %s
                    """,
                    (f"%{search}%",),
                )
                counts = cur.fetchone()
                result["search"] = {
                    "query": search,
                    "matching_conversations": counts["conversations"],
                    "total_user_message_hits": counts["messages"],
                    "top_matching_conversations": [
                        {
                            "conversation_id": row["conversation_id"],
                            "hit_count": row["hit_count"],
                        }
                        for row in top_matches
                    ],
                }

            return result


if __name__ == "__main__":
    main()
